-- ============================================================================
-- Backend/schema.sql — Campus Rankers Hub (campusrankers.com)
-- Target: DigitalOcean Managed PostgreSQL (postgres:18 Debian for local parity)
--
-- Authored: 2026-05-02 — Phase 1 of postgres-migration-v2
-- Source-of-truth spec: migrations/postgres-v2/phase-1-SPEC.md
--
-- IDEMPOTENCY MODEL (read this before editing):
--   This file is "re-runnable without error" against a target that already
--   matches its definition — IF NOT EXISTS guards plus the DROP/CREATE trigger
--   pattern make a second `psql -v ON_ERROR_STOP=1 -f schema.sql` exit 0 with
--   no schema changes (besides trigger recreation, which mutates pg_trigger by
--   design but is otherwise inert).
--
--   It is NOT "convergent" — if a table or column already exists with a
--   DIFFERENT shape (drift), this file silently accepts the drift; it does
--   not repair. To change a column type, drop a column, or alter a constraint,
--   write a forward-migration script in its own phase. DO NOT edit this file
--   expecting retro-application against existing databases.
--
-- DROP POLICY:
--   The ONLY DROP statements in this file are
--     DROP TRIGGER IF EXISTS <name> ON <table>;
--   because Postgres has no CREATE TRIGGER IF NOT EXISTS. No DROP TABLE,
--   no DROP COLUMN, no DROP INDEX, no DROP CONSTRAINT. Per CONSTITUTION §5.
--
-- WIRE FORMAT:
--   Column names are snake_case in the database. The application layer
--   (Phase 3 routers) converts to camelCase on the wire — see CONSTITUTION §4.
--
-- TIMESTAMPS:
--   TIMESTAMPTZ everywhere (DO Managed Postgres defaults to UTC).
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 0. Shared trigger function — keep updated_at fresh on every UPDATE.
--    CREATE OR REPLACE makes this natively idempotent.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ----------------------------------------------------------------------------
-- 1. schools — institutions (Northeastern, RPI, etc.)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schools (
    id          BIGSERIAL PRIMARY KEY,
    name        TEXT        NOT NULL,
    slug        TEXT        NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_schools_updated_at ON schools;
CREATE TRIGGER trg_schools_updated_at
    BEFORE UPDATE ON schools
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 2. organizations — league authorities (CVAL, NECC, NACE, ECAC, ...)
--    `games` is bounded by V1 (Valorant + LoL); when we expand the multi-game
--    roadmap, this CHECK is edited in its own phase.
-- ----------------------------------------------------------------------------
-- NOTE for Phase 3 router authors: `games` has a DEFAULT of ARRAY[]::TEXT[],
-- but the CHECK (cardinality > 0) makes that default UNUSABLE — an INSERT
-- that omits `games` will fail. The default is intentional (it satisfies
-- NOT NULL during multi-row inserts that explicitly set games per row), but
-- application code MUST always supply a non-empty games array.
CREATE TABLE IF NOT EXISTS organizations (
    id            BIGSERIAL PRIMARY KEY,
    name          TEXT        NOT NULL,
    abbreviation  TEXT        NOT NULL,
    slug          TEXT        NOT NULL UNIQUE,
    games         TEXT[]      NOT NULL DEFAULT ARRAY[]::TEXT[]
                              CHECK (cardinality(games) > 0)
                              CHECK (games <@ ARRAY['valorant', 'lol']::TEXT[]),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_organizations_updated_at ON organizations;
CREATE TRIGGER trg_organizations_updated_at
    BEFORE UPDATE ON organizations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 3. seasons — per-organization terms (Fall 2026, Spring 2027, ...)
--
--    INVARIANT: at most one row may have active=TRUE per org. Enforced at the
--    DB level by a partial unique index. Application code should still validate
--    for friendly error messages, but the DB is the final guard.
--
--    `semester` is locked to fall/spring/summer (Decision #4 — no winter).
--    `year` is bounded 2000..2100 as a sanity check.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seasons (
    id          BIGSERIAL PRIMARY KEY,
    org_id      BIGINT      NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    year        INTEGER     NOT NULL CHECK (year >= 2000 AND year <= 2100),
    semester    TEXT        NOT NULL CHECK (semester IN ('fall', 'spring', 'summer')),
    label       TEXT        NOT NULL,
    active      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_seasons_org_active
    ON seasons (org_id, active);

-- One active season per org (DB-level enforcement, stronger than app-side only).
CREATE UNIQUE INDEX IF NOT EXISTS uq_seasons_one_active_per_org
    ON seasons (org_id) WHERE active;

DROP TRIGGER IF EXISTS trg_seasons_updated_at ON seasons;
CREATE TRIGGER trg_seasons_updated_at
    BEFORE UPDATE ON seasons
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 4. conferences — flat with `tier` label (per ADR 2026-04-18). Slug is
--    unique only within an organization.
--
--    `kind` is freeform TEXT — the canonical list of values (D1, D2, Premier,
--    Plus, Open, ...) is not yet defined. CHECK constraint to be added in a
--    future phase once the values stabilize.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conferences (
    id          BIGSERIAL PRIMARY KEY,
    org_id      BIGINT      NOT NULL REFERENCES organizations(id) ON DELETE RESTRICT,
    name        TEXT        NOT NULL,
    short_name  TEXT,
    slug        TEXT        NOT NULL,
    tier        TEXT,
    kind        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_conferences_slug_org
    ON conferences (org_id, slug);

DROP TRIGGER IF EXISTS trg_conferences_updated_at ON conferences;
CREATE TRIGGER trg_conferences_updated_at
    BEFORE UPDATE ON conferences
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 5. teams — per-school team rosters per game.
--
--    `school_name` and `region` are denormalized snapshots from `schools` at
--    write time. NOT back-filled if `schools.name` is later renamed; the app
--    layer is responsible for re-syncing if a school is renamed.
--
--    `rating` is an ELO-style score maintained by application code.
--
--    `teams.league_slug` was on the prior WIP branch; it's a stale artifact
--    from the flat-leagues model. The modern hierarchy is
--    Org → Season → Conference via team_memberships. NOT included here.
--
--    Slug is unique only within a game (a "Northeastern" Val team and a
--    "Northeastern" LoL team can both exist with slug='northeastern').
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams (
    id           BIGSERIAL PRIMARY KEY,
    school_id    BIGINT      NOT NULL REFERENCES schools(id) ON DELETE RESTRICT,
    name         TEXT        NOT NULL,
    slug         TEXT        NOT NULL,
    game         TEXT        NOT NULL CHECK (game IN ('valorant', 'lol')),
    tier         TEXT,
    school_name  TEXT,                              -- denormalized snapshot
    region       TEXT,                              -- 'na', 'eu', etc.
    rating       NUMERIC,                           -- ELO-style; nullable
    wins         INTEGER     NOT NULL DEFAULT 0 CHECK (wins        >= 0),
    losses       INTEGER     NOT NULL DEFAULT 0 CHECK (losses      >= 0),
    map_wins     INTEGER     NOT NULL DEFAULT 0 CHECK (map_wins    >= 0),
    map_losses   INTEGER     NOT NULL DEFAULT 0 CHECK (map_losses  >= 0),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_teams_slug_game
    ON teams (slug, game);

DROP TRIGGER IF EXISTS trg_teams_updated_at ON teams;
CREATE TRIGGER trg_teams_updated_at
    BEFORE UPDATE ON teams
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 6. team_memberships — M2M: team belongs to a conference for a season.
--    Kept after teams leave for historical record.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_memberships (
    id             BIGSERIAL PRIMARY KEY,
    team_id        BIGINT      NOT NULL REFERENCES teams(id)        ON DELETE CASCADE,
    conference_id  BIGINT      NOT NULL REFERENCES conferences(id)  ON DELETE RESTRICT,
    season_id      BIGINT      NOT NULL REFERENCES seasons(id)      ON DELETE RESTRICT,
    active         BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_team_memberships
    ON team_memberships (team_id, conference_id, season_id);

CREATE INDEX IF NOT EXISTS idx_team_memberships_active
    ON team_memberships (season_id, conference_id) WHERE active;

DROP TRIGGER IF EXISTS trg_team_memberships_updated_at ON team_memberships;
CREATE TRIGGER trg_team_memberships_updated_at
    BEFORE UPDATE ON team_memberships
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 7. players — per-game player records.
--
--    `riot_puuid` is the upsert target for ingestion (never assume name is
--    unique). It's nullable: admin-entered players may not have a PUUID until
--    they go through RSO. Postgres UNIQUE permits multiple NULLs, so admin-
--    entered no-PUUID rows coexist freely; the constraint only fires once a
--    real PUUID is set.
--
--    `slug` populated by Phase 5 RSO flow; nullable until then.
--    `rating` is an ELO-style score maintained by application code.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS players (
    id            BIGSERIAL PRIMARY KEY,
    name          TEXT        NOT NULL,
    slug          TEXT,
    riot_puuid    TEXT        UNIQUE,                   -- nullable; sparse-unique by Postgres semantics
    riot_id       TEXT,                                 -- 'gameName#tagLine'
    display_name  TEXT,
    role          TEXT,                                 -- 'Duelist', 'Top', etc.
    game          TEXT        NOT NULL CHECK (game IN ('valorant', 'lol')),
    active        BOOLEAN     NOT NULL DEFAULT TRUE,
    rating        NUMERIC,                              -- ELO-style; nullable
    stats         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_players_updated_at ON players;
CREATE TRIGGER trg_players_updated_at
    BEFORE UPDATE ON players
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 8. team_players — M2M: player↔team↔season. Replaces the Mongo `teamIds[]`
--    array with a real junction table for FK integrity and per-relationship
--    attributes.
--
--    A player can leave a team mid-season (set left_at) and rejoin a different
--    team (new row, possibly different season). Per-game-per-season uniqueness
--    is intentionally NOT enforced here (Decision #7 — deferred); it can be
--    added later as a single CREATE UNIQUE INDEX migration if a real conflict
--    surfaces.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_players (
    id          BIGSERIAL PRIMARY KEY,
    team_id     BIGINT      NOT NULL REFERENCES teams(id)    ON DELETE CASCADE,
    player_id   BIGINT      NOT NULL REFERENCES players(id)  ON DELETE CASCADE,
    season_id   BIGINT      NOT NULL REFERENCES seasons(id)  ON DELETE RESTRICT,
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    left_at     TIMESTAMPTZ,                             -- non-null = left team
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Same player cannot be on the same team in the same season twice without
-- leaving first. Re-joining (after leaving) is allowed via a new row.
CREATE UNIQUE INDEX IF NOT EXISTS uq_team_players_active
    ON team_players (team_id, player_id, season_id) WHERE left_at IS NULL;

DROP TRIGGER IF EXISTS trg_team_players_updated_at ON team_players;
CREATE TRIGGER trg_team_players_updated_at
    BEFORE UPDATE ON team_players
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 9. player_consents — RSO consent gate (Phase 5 populates and enforces).
--
--    Created in Phase 1 so all `players.id` FKs are stable from the start.
--
--    AUDIT HISTORY: multiple rows allowed per player to record grant→revoke→
--    re-grant lifecycle. The partial unique index permits at most ONE active
--    (non-revoked) row per player at any time, but historical rows accumulate.
--
--    `riot_puuid` is denormalized at grant time and is IMMUTABLE for audit —
--    if a player's puuid changes (rare) we record a new consent row, not edit.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_consents (
    id           BIGSERIAL PRIMARY KEY,
    player_id    BIGINT      NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    granted_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at   TIMESTAMPTZ,
    riot_puuid   TEXT        NOT NULL,                  -- denormalized snapshot at grant time
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Active grant uniqueness: at most one non-revoked row per player.
CREATE UNIQUE INDEX IF NOT EXISTS uq_player_consents_active
    ON player_consents (player_id) WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_player_consents_player
    ON player_consents (player_id, granted_at DESC);

DROP TRIGGER IF EXISTS trg_player_consents_updated_at ON player_consents;
CREATE TRIGGER trg_player_consents_updated_at
    BEFORE UPDATE ON player_consents
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 10. matches — head-to-head match records.
--
--     PARTIAL UNIQUE on `riot_match_id`: admin matches have NULL riot_match_id
--     (manual entry), Riot-ingested matches have a real string ID. We index
--     only the non-NULL rows so the index stays small and intent-clear.
--     (Standard Postgres UNIQUE already allows multiple NULLs, so a non-
--     partial unique would be functionally OK here — the 409 bug in
--     PROGRESS.md Graveyard #1 was a Mongo-specific issue where the unique
--     index on `matchId` needed `sparse: true`. We carry the partial-unique
--     pattern forward as good practice; do not switch to a non-partial
--     unique index without re-reading that history.)
--
--     `matches_dup_guard` (UNIQUE on team1_id, team2_id, match_date, game) is
--     a SAME-ORDER duplicate guard. It does NOT catch reversed-team rematches
--     ((A,B,date) vs (B,A,date)). The application layer (Phase 3) MUST
--     pre-check both orderings before insert (CONSTITUTION §3 invariant).
--
--     `team1_id <> team2_id` CHECK: a team cannot play itself.
--
--     `org_id`, `season_id`, `conference_id` are nullable for legacy matches
--     that predate the org/season/conference hierarchy.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS matches (
    id              BIGSERIAL PRIMARY KEY,
    team1_id        BIGINT      NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    team2_id        BIGINT      NOT NULL REFERENCES teams(id) ON DELETE RESTRICT,
    team1_score     INTEGER     NOT NULL DEFAULT 0 CHECK (team1_score >= 0),
    team2_score     INTEGER     NOT NULL DEFAULT 0 CHECK (team2_score >= 0),
    format          TEXT        NOT NULL CHECK (format IN ('bo1', 'bo3', 'bo5')),
    match_date      TIMESTAMPTZ NOT NULL,
    game            TEXT        NOT NULL CHECK (game IN ('valorant', 'lol')),
    org_id          BIGINT      REFERENCES organizations(id) ON DELETE RESTRICT,
    season_id       BIGINT      REFERENCES seasons(id)       ON DELETE RESTRICT,
    conference_id   BIGINT      REFERENCES conferences(id)   ON DELETE RESTRICT,
    riot_match_id   TEXT,                                       -- nullable for admin entries
    source          TEXT        NOT NULL DEFAULT 'admin' CHECK (source IN ('admin', 'riot')),
    league_name     TEXT,                                       -- denormalized rendered league name (legacy fallback)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (team1_id <> team2_id)
);

-- Sparse-unique on riot_match_id: only Riot-source matches participate; admin
-- matches with NULL coexist freely. THIS PARTIAL PREDICATE IS REQUIRED — see
-- the bug-409 history in the trigger comment above.
CREATE UNIQUE INDEX IF NOT EXISTS uq_matches_riot_match_id
    ON matches (riot_match_id) WHERE riot_match_id IS NOT NULL;

-- Same-order duplicate guard. Reversed-team duplicates remain the app layer's
-- responsibility (CONSTITUTION §3).
CREATE UNIQUE INDEX IF NOT EXISTS uq_matches_dup_guard
    ON matches (team1_id, team2_id, match_date, game);

CREATE INDEX IF NOT EXISTS idx_matches_match_date
    ON matches (match_date DESC);
CREATE INDEX IF NOT EXISTS idx_matches_team1
    ON matches (team1_id, match_date DESC);
CREATE INDEX IF NOT EXISTS idx_matches_team2
    ON matches (team2_id, match_date DESC);

DROP TRIGGER IF EXISTS trg_matches_updated_at ON matches;
CREATE TRIGGER trg_matches_updated_at
    BEFORE UPDATE ON matches
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 11. player_match_stats — THIN POLYMORPHIC CORE.
--
--     Path 2 architecture (Decision #9): this core holds only cross-game
--     columns. Per-game stats (K/D/A, agent/champion, ACS/CS/gold, etc.) live
--     in 1:1-related per-game detail tables: pms_valorant_details,
--     pms_lol_details. Future games (Rocket League, TFT, Smash, OW, CoD,
--     Fortnite, TF2) add their own pms_<game>_details tables in their own
--     phase, with no rework of this core.
--
--     APP-LEVEL INVARIANT (not DB-enforced): for every row in
--     player_match_stats, the application MUST insert exactly one
--     corresponding row into pms_<game>_details matching the core's `game`
--     value. The DB enforces "at most one detail row per pms row" via the
--     UNIQUE FK in each detail table; "exactly one" and "correct detail
--     table for game" are app responsibilities. Phase 3 admin/ingestion
--     code carries this contract.
--
--     `team_name` is a denormalized snapshot of teams.name at write time
--     (NOT back-filled if the team is renamed). For match-detail rendering
--     without a join.
--
--     `map_name=''` (empty string) is intentional for series rows where one
--     row represents the whole series rather than per-map detail. The unique
--     constraint relies on this: (match_id, player_id, '') is a single row.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player_match_stats (
    id          BIGSERIAL PRIMARY KEY,
    match_id    BIGINT      NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
    player_id   BIGINT      NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
    team_id     BIGINT      NOT NULL REFERENCES teams(id)   ON DELETE RESTRICT,
    team_name   TEXT,                                       -- denormalized snapshot
    game        TEXT        NOT NULL CHECK (game IN ('valorant', 'lol')),
    map_name    TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pms
    ON player_match_stats (match_id, player_id, map_name);

CREATE INDEX IF NOT EXISTS idx_pms_player
    ON player_match_stats (player_id, match_id);

DROP TRIGGER IF EXISTS trg_player_match_stats_updated_at ON player_match_stats;
CREATE TRIGGER trg_player_match_stats_updated_at
    BEFORE UPDATE ON player_match_stats
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 12. pms_valorant_details — 1:1 with player_match_stats for Valorant rows.
--
--     UNIQUE(pms_id) enforces the 1:1 relationship. ON DELETE CASCADE so the
--     detail row vanishes when the core row is deleted (same lifecycle).
--
--     `agent` is NOT NULL — every Val match has an agent picked.
--     `acs`, `side` are nullable (admin entry may omit ACS; series rows have
--     no single side).
--     `details JSONB` holds non-essential extras (ADR, HS%, first kills,
--     plant/defuse counts, etc.) without schema churn.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pms_valorant_details (
    id          BIGSERIAL PRIMARY KEY,
    pms_id      BIGINT      NOT NULL UNIQUE REFERENCES player_match_stats(id) ON DELETE CASCADE,
    kills       INTEGER     NOT NULL DEFAULT 0 CHECK (kills   >= 0),
    deaths      INTEGER     NOT NULL DEFAULT 0 CHECK (deaths  >= 0),
    assists     INTEGER     NOT NULL DEFAULT 0 CHECK (assists >= 0),
    agent       TEXT        NOT NULL,
    acs         INTEGER     CHECK (acs >= 0),
    side        TEXT        CHECK (side IS NULL OR side IN ('attacker', 'defender')),
    details     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_pms_valorant_details_updated_at ON pms_valorant_details;
CREATE TRIGGER trg_pms_valorant_details_updated_at
    BEFORE UPDATE ON pms_valorant_details
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 13. pms_lol_details — 1:1 with player_match_stats for LoL rows.
--
--     `champion` is NOT NULL — every LoL match has a champion picked.
--     `cs`, `gold`, `lane` are nullable for admin entry without those metrics.
--     `details JSONB` holds non-essential extras (KP%, vision score, damage
--     shares, ward stats, KDA ratio, etc.).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pms_lol_details (
    id          BIGSERIAL PRIMARY KEY,
    pms_id      BIGINT      NOT NULL UNIQUE REFERENCES player_match_stats(id) ON DELETE CASCADE,
    kills       INTEGER     NOT NULL DEFAULT 0 CHECK (kills   >= 0),
    deaths      INTEGER     NOT NULL DEFAULT 0 CHECK (deaths  >= 0),
    assists     INTEGER     NOT NULL DEFAULT 0 CHECK (assists >= 0),
    champion    TEXT        NOT NULL,
    cs          INTEGER     CHECK (cs   >= 0),
    gold        INTEGER     CHECK (gold >= 0),
    lane        TEXT,                                       -- 'Top', 'Jungle', 'Mid', 'ADC', 'Support'
    details     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_pms_lol_details_updated_at ON pms_lol_details;
CREATE TRIGGER trg_pms_lol_details_updated_at
    BEFORE UPDATE ON pms_lol_details
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 14. tournaments — denormalized JSONB blobs for teams and matches.
--
--     This is a deliberate punt for V1 (Decision #5). No FK integrity, no
--     indexable lookup inside the JSONB. Candidate for normalization in a
--     post-launch "tournament v2" feature.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tournaments (
    id          BIGSERIAL PRIMARY KEY,
    name        TEXT        NOT NULL,
    slug        TEXT        NOT NULL UNIQUE,
    game        TEXT        NOT NULL CHECK (game IN ('valorant', 'lol')),
    start_date  DATE,
    end_date    DATE,
    teams       JSONB       NOT NULL DEFAULT '[]'::jsonb,
    matches     JSONB       NOT NULL DEFAULT '[]'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_tournaments_updated_at ON tournaments;
CREATE TRIGGER trg_tournaments_updated_at
    BEFORE UPDATE ON tournaments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ----------------------------------------------------------------------------
-- 15. rso_tokens — Riot Sign-On (RSO) OAuth token storage.
--
--     PUUID is the primary key (one token row per Riot user). NO foreign key
--     to players.riot_puuid — the RSO callback receives a PUUID before any
--     `players` row may exist (the player record is created/looked up FROM
--     the token). A hard FK would make the very first sign-in flow circular.
--     The relationship is logical-only; Phase 3/5 routers look up the player
--     by riot_puuid after the token is stored.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rso_tokens (
    puuid          TEXT        PRIMARY KEY,
    access_token   TEXT        NOT NULL,
    refresh_token  TEXT,
    expires_at     TIMESTAMPTZ NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_rso_tokens_updated_at ON rso_tokens;
CREATE TRIGGER trg_rso_tokens_updated_at
    BEFORE UPDATE ON rso_tokens
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


COMMIT;

-- ============================================================================
-- End of schema.sql.
-- 15 tables, 1 shared trigger function, per-table BEFORE UPDATE triggers,
-- partial unique indexes for sparse-uniqueness and active-state guards.
-- ============================================================================
